export interface TagItem {
  name: string;
  translation: string;
}

export interface TagCategory {
  title: string;
  tags: TagItem[];
  color: string;
}

export const TAG_CATEGORIES: TagCategory[] = [
  {
    title: 'Composition & Perspective',
    color: 'from-amber-400/20 to-orange-500/20 border-amber-400/30',
    tags: [
      { name: 'split screen', translation: 'разделенный экран' },
      { name: 'multiple views', translation: 'несколько ракурсов' },
      { name: 'three views', translation: 'вид с трех сторон' },
      { name: 'character sheet', translation: 'чар-лист (концепт)' },
      { name: 'cut-in', translation: 'вставка (кадр в кадре)' },
      { name: 'left half', translation: 'левая половина кадра' },
      { name: 'right half', translation: 'правая половина кадра' },
      { name: 'foreground focus', translation: 'фокус на переднем плане' },
      { name: 'background focus', translation: 'фокус на заднем плане' },
      { name: 'depth of field', translation: 'глубина резкости' },
      { name: 'bokeh', translation: 'боке (размытие)' },
      { name: 'side-by-side', translation: 'бок о бок' },
      { name: 'back-to-back', translation: 'спина к спине' },
      { name: 'facing each other', translation: 'лицом друг к другу' },
      { name: 'eye contact', translation: 'зрительный контакт' },
      { name: 'looking away', translation: 'взгляд в сторону' },
      { name: 'profile', translation: 'профиль' },
      { name: 'from behind', translation: 'вид со спины' },
      { name: 'from side', translation: 'вид сбоку' },
      { name: 'from above', translation: 'вид сверху (top-down)' },
      { name: 'from below', translation: 'вид снизу (low angle)' },
      { name: 'bird\'s-eye view', translation: 'вид с высоты полета' },
      { name: 'worm\'s-eye view', translation: 'вид от земли' },
      { name: 'dutch angle', translation: 'голландский угол (наклон)' },
      { name: 'fisheye', translation: 'рыбий глаз (линза)' },
      { name: 'wide shot', translation: 'общий план' },
      { name: 'ultra-wide shot', translation: 'сверхширокий план' },
      { name: 'full body', translation: 'в полный рост' },
      { name: 'cowboy shot', translation: 'кадр по бедра (вестерн)' },
      { name: 'upper body', translation: 'по пояс' },
      { name: 'medium shot', translation: 'средний план' },
      { name: 'close-up', translation: 'крупный план (лицо)' },
      { name: 'extreme close-up', translation: 'макро (глаза/губы)' },
      { name: 'portrait', translation: 'портрет' },
      { name: 'selfie', translation: 'селфи' }
    ]
  },
  {
    title: 'Anatomy & Body (Female)',
    color: 'from-cyan-400/20 to-blue-500/20 border-cyan-400/30',
    tags: [
      { name: '1girl', translation: '1 девушка' },
      { name: '2girls', translation: '2 девушки' },
      { name: '3girls', translation: '3 девушки' },
      { name: 'mature female', translation: 'зрелая женщина' },
      { name: 'milf', translation: 'милфа' },
      { name: 'tomboy', translation: 'пацанка' },
      { name: 'long hair', translation: 'длинные волосы' },
      { name: 'short hair', translation: 'короткие волосы' },
      { name: 'bob cut', translation: 'стрижка боб' },
      { name: 'hime cut', translation: 'прямая челка (принцесса)' },
      { name: 'pixie cut', translation: 'пикси (очень коротко)' },
      { name: 'very long hair', translation: 'очень длинные волосы' },
      { name: 'absurdly long hair', translation: 'волосы до пят' },
      { name: 'twintails', translation: 'два хвостика' },
      { name: 'drill hair', translation: 'волосы-дрели (кудри)' },
      { name: 'ponytail', translation: 'конский хвост' },
      { name: 'side ponytail', translation: 'хвост на боку' },
      { name: 'braid', translation: 'коса' },
      { name: 'twin braids', translation: 'две косички' },
      { name: 'messy hair', translation: 'растрепанные волосы' },
      { name: 'ahoge', translation: 'ахоге (антенка)' },
      { name: 'blonde hair', translation: 'светлые волосы' },
      { name: 'platinum blonde', translation: 'платиновый блонд' },
      { name: 'brunette', translation: 'брюнетка' },
      { name: 'black hair', translation: 'черные волосы' },
      { name: 'pink hair', translation: 'розовые волосы' },
      { name: 'white hair', translation: 'белые волосы' },
      { name: 'silver hair', translation: 'серебристые волосы' },
      { name: 'red hair', translation: 'рыжие волосы' },
      { name: 'blue hair', translation: 'синие волосы' },
      { name: 'purple hair', translation: 'фиолетовые волосы' },
      { name: 'green hair', translation: 'зеленые волосы' },
      { name: 'multicolored hair', translation: 'разноцветные волосы' },
      { name: 'blue eyes', translation: 'голубые глаза' },
      { name: 'red eyes', translation: 'красные глаза' },
      { name: 'green eyes', translation: 'зеленые глаза' },
      { name: 'yellow eyes', translation: 'желтые глаза' },
      { name: 'purple eyes', translation: 'фиолетовые глаза' },
      { name: 'heterochromia', translation: 'разные глаза' },
      { name: 'slit pupils', translation: 'змеиные зрачки' },
      { name: 'heart-shaped pupils', translation: 'зрачки-сердечки' },
      { name: 'pale skin', translation: 'бледная кожа' },
      { name: 'tan', translation: 'загар' },
      { name: 'tanlines', translation: 'следы от купальника' },
      { name: 'dark skin', translation: 'темная кожа' },
      { name: 'freckles', translation: 'веснушки' },
      { name: 'slim', translation: 'стройная' },
      { name: 'skinny', translation: 'худая' },
      { name: 'curvy', translation: 'с формами' },
      { name: 'voluptuous', translation: 'пышная' },
      { name: 'fit', translation: 'подтянутая' },
      { name: 'muscular female', translation: 'мускулистая женщина' },
      { name: 'abs', translation: 'пресс' },
      { name: 'chubby', translation: 'полненькая' },
      { name: 'hourglass figure', translation: 'песочные часы' },
      { name: 'thick thighs', translation: 'пышные бедра' },
      { name: 'wide hips', translation: 'широкие бедра' },
      { name: 'gap between legs', translation: 'просвет между бедер' },
      { name: 'flat chest', translation: 'плоская грудь' },
      { name: 'small breasts', translation: 'маленькая грудь' },
      { name: 'medium breasts', translation: 'средняя грудь' },
      { name: 'large breasts', translation: 'большая грудь' },
      { name: 'huge breasts', translation: 'огромная грудь' },
      { name: 'hanging breasts', translation: 'обвисшая грудь' },
      { name: 'sideboob', translation: 'вид груди сбоку' },
      { name: 'underboob', translation: 'вид груди снизу' },
      { name: 'cat ears', translation: 'кошачьи ушки' },
      { name: 'dog ears', translation: 'собачьи ушки' },
      { name: 'fox ears', translation: 'лисьи ушки' },
      { name: 'elf ears', translation: 'эльфийские уши' },
      { name: 'demon horns', translation: 'рога демона' },
      { name: 'wings', translation: 'крылья' },
      { name: 'tail', translation: 'хвост' }
    ]
  },
  {
    title: 'Anatomy & Body (Boys)',
    color: 'from-emerald-400/20 to-teal-500/20 border-emerald-400/30',
    tags: [
      { name: '1boy', translation: '1 парень' },
      { name: '2boys', translation: '2 парня' },
      { name: 'handsome male', translation: 'красивый мужчина' },
      { name: 'muscular male', translation: 'мускулистый мужчина' },
      { name: 'bara', translation: 'бара (очень мощный)' },
      { name: 'skinny male', translation: 'худой парень' },
      { name: 'tall male', translation: 'высокий парень' },
      { name: 'short male', translation: 'низкий парень' },
      { name: 'bishounen', translation: 'красивый женственный парень' },
      { name: 'abs', translation: 'пресс (кубики)' },
      { name: 'v-line', translation: 'V-образная линия (паховая)' },
      { name: 'broad shoulders', translation: 'широкие плечи' },
      { name: 'pectoralis', translation: 'грудные мышцы' },
      { name: 'veiny arms', translation: 'руки в венах' },
      { name: 'facial hair', translation: 'растительность на лице' },
      { name: 'beard', translation: 'борода' },
      { name: 'stubble', translation: 'щетина' },
      { name: 'mustache', translation: 'усы' },
      { name: 'hairy chest', translation: 'волосатая грудь' },
      { name: 'slicked-back hair', translation: 'зализанные волосы' },
      { name: 'undercut', translation: 'андеркат (стрижка)' }
    ]
  },
  {
    title: 'Clothing Styles',
    color: 'from-blue-400/20 to-indigo-500/20 border-blue-400/30',
    tags: [
      { name: 'casual wear', translation: 'повседневная одежда' },
      { name: 'streetwear', translation: 'уличная мода' },
      { name: 'formal wear', translation: 'строгий стиль' },
      { name: 'school uniform', translation: 'школьная форма' },
      { name: 'sailor collar', translation: 'матросский воротник' },
      { name: 'seifuku', translation: 'японская школьная форма' },
      { name: 'kimono', translation: 'кимоно' },
      { name: 'yukata', translation: 'юката' },
      { name: 'miko outfit', translation: 'наряд жрицы мико' },
      { name: 'maid outfit', translation: 'костюм горничной' },
      { name: 'french maid', translation: 'французская горничная' },
      { name: 'bunny suit', translation: 'костюм кролика' },
      { name: 'nurse outfit', translation: 'костюм медсестры' },
      { name: 'police uniform', translation: 'полицейская форма' },
      { name: 'military uniform', translation: 'военная форма' },
      { name: 'office lady', translation: 'офисный стиль' },
      { name: 'business suit', translation: 'деловой костюм' },
      { name: 'tuxedo', translation: 'смокинг' },
      { name: 'wedding dress', translation: 'свадебное платье' },
      { name: 'gothic lolita', translation: 'готическая лолита' },
      { name: 'punk style', translation: 'панк стиль' },
      { name: 'cyberpunk style', translation: 'киберпанк стиль' },
      { name: 'fantasy armor', translation: 'фэнтези броня' },
      { name: 'cheongsam', translation: 'ципао (китайское платье)' },
      { name: 'sportswear', translation: 'спортивная одежда' },
      { name: 'tracksuit', translation: 'спортивный костюм' },
      { name: 'gym uniform', translation: 'форма для физкультуры' },
      { name: 'swimsuit', translation: 'купальник' },
      { name: 'bikini', translation: 'бикини' },
      { name: 'micro bikini', translation: 'микро-бикини' },
      { name: 'competition swimsuit', translation: 'спортивный купальник' },
      { name: 'sling bikini', translation: 'бикини на бретельках' },
      { name: 'front-tied bikini', translation: 'бикини с завязкой спереди' }
    ]
  },
  {
    title: 'Tops & Bottoms',
    color: 'from-sky-400/20 to-blue-500/20 border-sky-400/30',
    tags: [
      { name: 'hoodie', translation: 'худи' },
      { name: 'sweater', translation: 'свитер' },
      { name: 'turtleneck', translation: 'водолазка' },
      { name: 'virgin killer sweater', translation: 'свитер с открытой спиной' },
      { name: 'crop top', translation: 'кроп-топ' },
      { name: 'tank top', translation: 'майка' },
      { name: 'halter top', translation: 'топ через шею' },
      { name: 'tube top', translation: 'топ без лямок' },
      { name: 't-shirt', translation: 'футболка' },
      { name: 'shirt', translation: 'рубашка' },
      { name: 'blouse', translation: 'блузка' },
      { name: 'off-shoulder shirt', translation: 'рубашка без плеч' },
      { name: 'unbuttoned shirt', translation: 'расстегнутая рубашка' },
      { name: 'see-through shirt', translation: 'прозрачная рубашка' },
      { name: 'leather jacket', translation: 'кожаная куртка' },
      { name: 'denim jacket', translation: 'джинсовка' },
      { name: 'coat', translation: 'пальто' },
      { name: 'trench coat', translation: 'плащ' },
      { name: 'cape', translation: 'накидка' },
      { name: 'mini skirt', translation: 'мини-юбка' },
      { name: 'pleated skirt', translation: 'плиссированная юбка' },
      { name: 'pencil skirt', translation: 'юбка-карандаш' },
      { name: 'denim shorts', translation: 'джинсовые шорты' },
      { name: 'dolphin shorts', translation: 'короткие спортивные шорты' },
      { name: 'hot pants', translation: 'очень короткие шорты' },
      { name: 'jeans', translation: 'джинсы' },
      { name: 'low-rise jeans', translation: 'джинсы с низкой талией' },
      { name: 'cargo pants', translation: 'брюки-карго' },
      { name: 'leggings', translation: 'легинсы' },
      { name: 'yoga pants', translation: 'штаны для йоги' },
      { name: 'buruma', translation: 'японские спортивные трусы' }
    ]
  },
  {
    title: 'Intimates & Lingerie',
    color: 'from-purple-400/20 to-fuchsia-500/20 border-purple-400/30',
    tags: [
      { name: 'lingerie', translation: 'нижнее белье' },
      { name: 'lace lingerie', translation: 'кружевное белье' },
      { name: 'babydoll', translation: 'беби-долл' },
      { name: 'chemise', translation: 'сорочка' },
      { name: 'bra', translation: 'бюстгальтер' },
      { name: 'strapless bra', translation: 'лифчик без лямок' },
      { name: 'sports bra', translation: 'спортивный лифчик' },
      { name: 'front-opening bra', translation: 'застежка спереди' },
      { name: 'shelf bra', translation: 'открытый лифчик' },
      { name: 'panties', translation: 'трусики' },
      { name: 'thong', translation: 'стринги' },
      { name: 'g-string', translation: 'G-стринги' },
      { name: 'high-waisted panties', translation: 'высокая талия' },
      { name: 'frilled panties', translation: 'трусики с рюшами' },
      { name: 'low-leg panties', translation: 'трусики с низким вырезом' },
      { name: 'crotchless panties', translation: 'трусики с вырезом (интим)' },
      { name: 'panties under skirt', translation: 'трусики из-под юбки' },
      { name: 'no panties', translation: 'без трусиков' },
      { name: 'garter belt', translation: 'пояс для чулок' },
      { name: 'thighhighs', translation: 'чулки выше колена' },
      { name: 'stockings', translation: 'чулки' },
      { name: 'fishnet stockings', translation: 'чулки в сеточку' },
      { name: 'pantyhose', translation: 'колготки' },
      { name: 'bodystocking', translation: 'чулок на все тело' },
      { name: 'stay-ups', translation: 'чулки на силиконе' },
      { name: 'white stockings', translation: 'белые чулки' },
      { name: 'black stockings', translation: 'черные чулки' },
      { name: 'striped stockings', translation: 'полосатые чулки' }
    ]
  },
  {
    title: 'Poses (Standard & Basic)',
    color: 'from-indigo-400/20 to-violet-500/20 border-indigo-400/30',
    tags: [
      { name: 'standing', translation: 'стоит' },
      { name: 'sitting', translation: 'сидит' },
      { name: 'lying on back', translation: 'лежит на спине' },
      { name: 'lying on stomach', translation: 'лежит на животе' },
      { name: 'lying on side', translation: 'лежит на боку' },
      { name: 'kneeling', translation: 'на коленях' },
      { name: 'all fours', translation: 'на четвереньках' },
      { name: 'squatting', translation: 'на корточках' },
      { name: 'crouching', translation: 'пригнувшись' },
      { name: 'leaning forward', translation: 'наклон вперед' },
      { name: 'leaning back', translation: 'отклонившись назад' },
      { name: 'leaning against wall', translation: 'прислонившись к стене' },
      { name: 'arching back', translation: 'выгнув спину' },
      { name: 'arms up', translation: 'руки подняты' },
      { name: 'arms behind head', translation: 'руки за головой' },
      { name: 'arms behind back', translation: 'руки за спиной' },
      { name: 'arms crossed', translation: 'руки на груди' },
      { name: 'hands on hips', translation: 'руки на бедрах' },
      { name: 'hands on breasts', translation: 'руки на груди' },
      { name: 'hands on pussy', translation: 'руки на киске' },
      { name: 'hands on buttocks', translation: 'руки на заднице' },
      { name: 'legs up', translation: 'ноги подняты' },
      { name: 'legs spread', translation: 'ноги раздвинуты' },
      { name: 'crossed legs', translation: 'скрещенные ноги' },
      { name: 'one leg up', translation: 'одна нога поднята' },
      { name: 'bent over', translation: 'согнувшись' },
      { name: 'looking over shoulder', translation: 'взгляд через плечо' },
      { name: 'straddling', translation: 'сидит верхом' },
      { name: 'stretching', translation: 'потягивается' },
      { name: 'adjusting clothes', translation: 'поправляет одежду' }
    ]
  },
  {
    title: 'Poses (Complex & NSFW)',
    color: 'from-violet-500/20 to-purple-600/20 border-violet-400/30',
    tags: [
      { name: 'jack-o challenge', translation: 'поза Джек-О (наклон)' },
      { name: 'spread legs', translation: 'раздвинутые ноги' },
      { name: 'legs over head', translation: 'ноги за головой' },
      { name: 'bent over', translation: 'раком (наклон вперед)' },
      { name: 'doggy style', translation: 'поза догги' },
      { name: 'missionary', translation: 'миссионерская поза' },
      { name: 'cowgirl position', translation: 'поза наездницы' },
      { name: 'reverse cowgirl', translation: 'обратная наездница' },
      { name: 'mating press', translation: 'мейт-пресс' },
      { name: 'standing sex', translation: 'секс стоя' },
      { name: 'anal sex', translation: 'анальный секс' },
      { name: 'fellatio', translation: 'минет' },
      { name: 'cunnilingus', translation: 'кунилингус' },
      { name: 'deepthroat', translation: 'глубокий минет' },
      { name: 'paizuri', translation: 'пайзури (секс грудью)' },
      { name: 'handjob', translation: 'хендджоб (дрочка)' },
      { name: 'footjob', translation: 'футджоб (ногами)' },
      { name: 'titjob', translation: 'титджоб (грудью)' },
      { name: 'face down', translation: 'лицом вниз' },
      { name: 'shaking ass', translation: 'трясет задницей' },
      { name: 'presenting pussy', translation: 'показывает киску' },
      { name: 'presenting anus', translation: 'показывает анус' },
      { name: 'presenting breasts', translation: 'показывает грудь' },
      { name: 'bondage', translation: 'бондаж (связывание)' },
      { name: 'shibari', translation: 'шибари' }
    ]
  },
  {
    title: 'Interior & Furniture',
    color: 'from-teal-400/20 to-emerald-500/20 border-teal-400/30',
    tags: [
      { name: 'bed', translation: 'кровать' },
      { name: 'double bed', translation: 'двуспальная кровать' },
      { name: 'messy bed', translation: 'незаправленная кровать' },
      { name: 'on bed', translation: 'на кровати' },
      { name: 'sofa', translation: 'диван' },
      { name: 'leather sofa', translation: 'кожаный диван' },
      { name: 'on couch', translation: 'на диване' },
      { name: 'armchair', translation: 'кресло' },
      { name: 'chair', translation: 'стул' },
      { name: 'office chair', translation: 'офисное кресло' },
      { name: 'desk', translation: 'рабочий стол' },
      { name: 'dining table', translation: 'обеденный стол' },
      { name: 'bar counter', translation: 'барная стойка' },
      { name: 'bar stool', translation: 'барный стул' },
      { name: 'bookshelf', translation: 'книжная полка' },
      { name: 'mirror', translation: 'зеркало' },
      { name: 'full-length mirror', translation: 'зеркало в полный рост' },
      { name: 'window', translation: 'окно' },
      { name: 'curtains', translation: 'шторы' },
      { name: 'rug', translation: 'ковер' },
      { name: 'lamp', translation: 'лампа' },
      { name: 'ceiling fan', translation: 'потолочный вентилятор' },
      { name: 'bathtub', translation: 'ванна' },
      { name: 'shower', translation: 'душевая' },
      { name: 'toilet', translation: 'туалет' },
      { name: 'fireplace', translation: 'камин' },
      { name: 'closet', translation: 'шкаф' },
      { name: 'stairs', translation: 'лестница' }
    ]
  },
  {
    title: 'Locations & Environment',
    color: 'from-sky-500/20 to-blue-600/20 border-blue-500/30',
    tags: [
      { name: 'bedroom', translation: 'спальня' },
      { name: 'bathroom', translation: 'ванная' },
      { name: 'kitchen', translation: 'кухня' },
      { name: 'living room', translation: 'гостиная' },
      { name: 'classroom', translation: 'класс' },
      { name: 'library', translation: 'библиотека' },
      { name: 'office', translation: 'офис' },
      { name: 'gym', translation: 'спортзал' },
      { name: 'locker room', translation: 'раздевалка' },
      { name: 'poolside', translation: 'у бассейна' },
      { name: 'onsen', translation: 'онсэн (источник)' },
      { name: 'rooftop', translation: 'крыша' },
      { name: 'street', translation: 'улица' },
      { name: 'alleyway', translation: 'переулок' },
      { name: 'cyberpunk city', translation: 'киберпанк город' },
      { name: 'neon street', translation: 'неоновая улица' },
      { name: 'train interior', translation: 'вагон поезда' },
      { name: 'station', translation: 'станция' },
      { name: 'forest', translation: 'лес' },
      { name: 'park', translation: 'парк' },
      { name: 'beach', translation: 'пляж' },
      { name: 'ocean', translation: 'океан' },
      { name: 'underwater', translation: 'под водой' },
      { name: 'mountains', translation: 'горы' },
      { name: 'desert', translation: 'пустыня' },
      { name: 'ruins', translation: 'руины' },
      { name: 'castle', translation: 'замок' },
      { name: 'dungeon', translation: 'подземелье' },
      { name: 'space station', translation: 'космическая станция' },
      { name: 'bar', translation: 'бар / паб' },
      { name: 'cafe', translation: 'кафе' }
    ]
  },
  {
    title: 'Physiology & Fluids (NSFW)',
    color: 'from-rose-500/20 to-red-600/20 border-rose-500/30',
    tags: [
      { name: 'nsfw', translation: '18+' },
      { name: 'nude', translation: 'обнаженная' },
      { name: 'topless', translation: 'топлес' },
      { name: 'bottomless', translation: 'без низа' },
      { name: 'cleavage', translation: 'декольте' },
      { name: 'pussy', translation: 'киска' },
      { name: 'labia', translation: 'половые губы' },
      { name: 'clitoris', translation: 'клитор' },
      { name: 'vagina', translation: 'влагалище' },
      { name: 'anus', translation: 'анус' },
      { name: 'nipples', translation: 'соски' },
      { name: 'hard nipples', translation: 'твердые соски' },
      { name: 'areola', translation: 'ареолы' },
      { name: 'puffy areolas', translation: 'набухшие ареолы' },
      { name: 'cameltoe', translation: 'верблюжья лапка' },
      { name: 'spread pussy', translation: 'раздвинутая киска' },
      { name: 'fingering', translation: 'фингер (пальцем)' },
      { name: 'masturbation', translation: 'мастурбация' },
      { name: 'ahegao', translation: 'ахегао' },
      { name: 'tongue out', translation: 'язык высунут' },
      { name: 'saliva', translation: 'слюни' },
      { name: 'sweat', translation: 'пот' },
      { name: 'cum', translation: 'сперма' },
      { name: 'ejaculation', translation: 'эякуляция' },
      { name: 'creampie', translation: 'кримпай (внутрь)' },
      { name: 'anal creampie', translation: 'анальный кримпай' },
      { name: 'cum on face', translation: 'сперма на лице' },
      { name: 'cum on breasts', translation: 'сперма на груди' },
      { name: 'cum on body', translation: 'сперма на теле' },
      { name: 'cum on pussy', translation: 'сперма на киске' },
      { name: 'internal cum shot', translation: 'вид спермы внутри' },
      { name: 'precum', translation: 'предсемя' },
      { name: 'squirt', translation: 'сквирт' },
      { name: 'urine', translation: 'моча (фетиш)' },
      { name: 'breasts expansion', translation: 'увеличение груди' }
    ]
  },
  {
    title: 'Male Physiology (NSFW)',
    color: 'from-orange-500/20 to-red-500/20 border-orange-500/30',
    tags: [
      { name: 'penis', translation: 'член' },
      { name: 'large penis', translation: 'большой член' },
      { name: 'erection', translation: 'эрекция' },
      { name: 'throbbing', translation: 'пульсирующий' },
      { name: 'veiny penis', translation: 'пенис в венах' },
      { name: 'glans', translation: 'головка члена' },
      { name: 'testicles', translation: 'яички' },
      { name: 'scrotum', translation: 'мошонка' },
      { name: 'circumcised', translation: 'обрезанный' },
      { name: 'uncut', translation: 'необрезанный' },
      { name: 'bulge', translation: 'выпуклость (в штанах)' },
      { name: 'happy trail', translation: 'дорожка волос на животе' },
      { name: 'foreskin', translation: 'крайняя плоть' }
    ]
  },
  {
    title: 'Fetishes & Niche',
    color: 'from-purple-600/20 to-violet-800/20 border-purple-500/40',
    tags: [
      { name: 'futanari', translation: 'футанари' },
      { name: 'dickgirl', translation: 'девушка с членом' },
      { name: 'femboy', translation: 'фембой' },
      { name: 'trap', translation: 'трап' },
      { name: 'genderbender', translation: 'смена пола' },
      { name: 'crossdressing', translation: 'кроссдрессинг' },
      { name: 'tentacles', translation: 'тентакли' },
      { name: 'double penetration', translation: 'двойное проникновение' },
      { name: 'triple penetration', translation: 'тройное проникновение' },
      { name: 'group sex', translation: 'групповой секс' },
      { name: 'orgy', translation: 'оргия' },
      { name: 'gangbang', translation: 'гангбэнг' },
      { name: 'threesome', translation: 'втроем' },
      { name: 'forced', translation: 'принуждение' },
      { name: 'humiliation', translation: 'унижение' },
      { name: 'handcuffs', translation: 'наручники' },
      { name: 'collar', translation: 'ошейник' },
      { name: 'leash', translation: 'поводок' },
      { name: 'gag', translation: 'кляп' },
      { name: 'blindfold', translation: 'повязка на глазах' },
      { name: 'spanking', translation: 'шлепки' },
      { name: 'public use', translation: 'публичное использование' },
      { name: 'glory hole', translation: 'глори-хоул' }
    ]
  },
  {
    title: 'Quality & Lighting',
    color: 'from-sky-400/20 to-blue-400/20 border-sky-400/30',
    tags: [
      { name: 'masterpiece', translation: 'шедевр' },
      { name: 'best quality', translation: 'лучшее качество' },
      { name: 'ultra-detailed', translation: 'ультра-детализация' },
      { name: 'highres', translation: 'высокое разрешение' },
      { name: '8k', translation: '8K качество' },
      { name: 'absurdres', translation: 'абсурдное разрешение' },
      { name: 'cinematic lighting', translation: 'кино-освещение' },
      { name: 'dramatic lighting', translation: 'драматичный свет' },
      { name: 'neon lighting', translation: 'неоновый свет' },
      { name: 'volumetric lighting', translation: 'объемный свет' },
      { name: 'god rays', translation: 'лучи света' },
      { name: 'soft lighting', translation: 'мягкий свет' },
      { name: 'hard lighting', translation: 'жесткий свет' },
      { name: 'rim lighting', translation: 'контурный свет' },
      { name: 'backlighting', translation: 'контровой свет' },
      { name: 'lens flare', translation: 'блики линзы' },
      { name: 'ray tracing', translation: 'трассировка лучей' },
      { name: 'global illumination', translation: 'глобальное освещение' },
      { name: 'unreal engine 5', translation: 'движок Unreal 5' },
      { name: 'octane render', translation: 'рендер Octane' },
      { name: 'raytracing', translation: 'рейтрейсинг' }
    ]
  },
{
    title: "Height & Age Comparisons",
    color: "from-indigo-700 to-purple-900 border-indigo-500/50",
    tags: [
      { name: "different heights", translation: "Разница в росте" },
      { name: "height difference", translation: "Контраст роста" },
      { name: "tall man, short woman", translation: "Высокий парень, низкая девушка" },
      { name: "tall woman, short man", translation: "Высокая девушка, низкий парень" },
      { name: "huge height difference", translation: "Огромная разница в росте" },
      { name: "towering over", translation: "Возвышается над" },
      { name: "looking up at", translation: "Смотрит снизу вверх" },
      { name: "looking down at", translation: "Смотрит сверху вниз" },
      { name: "standing on tiptoes", translation: "Стоя на цыпочках" },
      { name: "head on shoulder", translation: "Голова на плече" },
      { name: "arm around waist", translation: "Рука на талии" },
      { name: "different ages", translation: "Разница в возрасте" },
      { name: "age difference", translation: "Контраст возраста" },
      { name: "mother and daughter", translation: "Мать и дочь" },
      { name: "father and son", translation: "Отец и сын" },
      { name: "young adult and elderly", translation: "Молодой и пожилой" },
      { name: "adult with youth", translation: "Взрослый с молодым" },
      { name: "mentorship", translation: "Наставничество" },
      { name: "generations", translation: "Поколения" },
      { name: "older man, younger woman", translation: "Старший мужчина, младшая женщина" },
      { name: "older woman, younger man", translation: "Старшая женщина, младший мужчина" },
    ]
  },
  {
    title: "Expressions & Emotions",
    color: "from-pink-700 to-rose-900 border-pink-500/50",
    tags: [
      { name: "expressionless", translation: "Безэмоциональный" },
      { name: "smiling", translation: "Улыбка" },
      { name: "seductive smile", translation: "Соблазнительная улыбка" },
      { name: "smirk", translation: "Ухмылка" },
      { name: "laughing", translation: "Смех" },
      { name: "crying", translation: "Плач" },
      { name: "sadness", translation: "Грусть" },
      { name: "angry", translation: "Гнев" },
      { name: "annoyed", translation: "Раздражение" },
      { name: "blushing", translation: "Смущение/Румянец" },
      { name: "deep blush", translation: "Сильное смущение" },
      { name: "embarrassed", translation: "Сбитый с толку" },
      { name: "surprised", translation: "Удивление" },
      { name: "scared", translation: "Испуг" },
      { name: "pouting", translation: "Надутые губы" },
      { name: "shouting", translation: "Крик" },
      { name: "thinking", translation: "Раздумья" },
      { name: "confused", translation: "Запутанный" },
      { name: "serious", translation: "Серьезный" },
      { name: "looking away", translation: "Смотрит в сторону" },
      { name: "eye contact", translation: "Зрительный контакт" },
      { name: "closed eyes", translation: "Закрытые глаза" },
      { name: "wink", translation: "Подмигивание" },
      { name: "tongue out", translation: "Высунутый язык" },
      { name: "naughty face", translation: "Шаловливое лицо" },
    ]
  },{
      title: "",
      tags: [],
      color: ""
    },{
    title: 'Negative & Fixes',
    color: 'from-rose-900/40 to-red-950/40 border-red-500/50',
    tags: [
      { name: 'worst quality', translation: 'худшее качество' },
      { name: 'low quality', translation: 'низкое качество' },
      { name: 'normal quality', translation: 'нормальное качество' },
      { name: 'monochrome', translation: 'монохром' },
      { name: 'grayscale', translation: 'градации серого' },
      { name: 'bad anatomy', translation: 'плохая анатомия' },
      { name: 'bad hands', translation: 'плохие руки' },
      { name: 'missing fingers', translation: 'отсутствуют пальцы' },
      { name: 'extra digit', translation: 'лишний палец' },
      { name: 'fewer digits', translation: 'меньше пальцев' },
      { name: 'mutated hands', translation: 'мутировавшие руки' },
      { name: 'poorly drawn face', translation: 'плохо нарисованное лицо' },
      { name: 'poorly drawn hands', translation: 'плохо нарисованные руки' },
      { name: 'mutation', translation: 'мутация' },
      { name: 'deformed', translation: 'деформировано' },
      { name: 'ugly', translation: 'уродливо' },
      { name: 'blurry', translation: 'размыто' },
      { name: 'out of focus', translation: 'не в фокусе' },
      { name: 'bad proportions', translation: 'плохие пропорции' },
      { name: 'extra limbs', translation: 'лишние конечности' },
      { name: 'cloned face', translation: 'клонированное лицо' },
      { name: 'watermark', translation: 'водяной знак' },
      { name: 'text', translation: 'текст' },
      { name: 'error', translation: 'ошибка' },
      { name: 'jpeg artifacts', translation: 'артефакты сжатия' },
      { name: 'signature', translation: 'подпись' },
      { name: 'username', translation: 'имя пользователя' },
      { name: 'censored', translation: 'цензура' },
      { name: 'bar censor', translation: 'цензура полосками' },
      { name: 'pixel censor', translation: 'пиксельная цензура' }
    ]
  }]
